# Generated by Django 5.1.5 on 2025-01-29 09:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier02', '0001_initial'),
        ('etude', '0002_evenement_redoute_mission_socle_de_securite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origine_risque', models.CharField(choices=[('state', 'État'), ('organized_crime', 'Crime organisé'), ('terrorist', 'Terroriste'), ('activist', 'Activiste'), ('competitor', 'Concurrence'), ('amateur', 'Amateur'), ('avenger', 'Vengeur'), ('pathological', 'Pathologique')], max_length=32, verbose_name='Origine du risque')),
                ('objectif_cible', models.TextField(verbose_name='Objectif cible')),
                ('motivation', models.PositiveSmallIntegerField(choices=[(0, 'non_définie'), (1, 'très_faible'), (2, 'faible'), (3, 'significative'), (4, 'forte')], default=0, verbose_name='Motivation')),
                ('ressources', models.PositiveSmallIntegerField(choices=[(0, 'non_définie'), (1, 'limitées'), (2, 'significatives'), (3, 'importantes'), (4, 'illimitées')], default=0, verbose_name='Ressources')),
                ('activite', models.PositiveSmallIntegerField(choices=[(0, 'non_définie'), (1, 'très_faible'), (2, 'faible'), (3, 'modérée'), (4, 'importante')], default=0, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Activité')),
                ('evenements_redoutes', models.ManyToManyField(blank=True, related_name='ro_to_couples', to='etude.evenement_redoute', verbose_name='Événements redoutés')),
            ],
        ),
        migrations.AddField(
            model_name='atelier02',
            name='SROV',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atelier02.roto'),
        ),
    ]
