# Generated by Django 5.1.5 on 2025-01-26 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(default='societe', max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BienSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entite', models.TextField()),
                ('vm_associe', models.TextField(verbose_name='Valeur métier associé')),
                ('description', models.TextField(default='description')),
                ('responsable', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evenement_redoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_associe', models.TextField(verbose_name='Valeur métier associé')),
                ('description', models.TextField(default='description')),
                ('impact', models.TextField(choices=[('social', 'Social'), ('service', 'Service'), ('juridique', 'Juridique'), ('gouvernance', 'Gouvernance'), ('financier', 'Financier'), ('reputation', 'Reputation'), ('humain', 'Humain'), ('materiel', 'Materiel')], default='reputation')),
                ('gravite', models.PositiveSmallIntegerField(choices=[(1, 'mineur'), (2, 'significatif'), (3, 'important'), (4, 'critique')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ValeurMetier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('mission', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('nature_vm', models.TextField(choices=[('processus', 'Processus'), ('information', 'Information')], default='information', verbose_name='nature ')),
                ('responsabe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etude.participant', verbose_name='Entité responsable')),
            ],
        ),
    ]
