# Generated by Django 5.1.5 on 2025-01-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtelierParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BienSupport',
        ),
        migrations.DeleteModel(
            name='Evenement_redoute',
        ),
        migrations.RemoveField(
            model_name='valeurmetier',
            name='responsabe',
        ),
    ]
