# Generated by Django 5.1.5 on 2025-01-26 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier01', '0001_initial'),
        ('etude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier01',
            name='particiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etude.participant', verbose_name='Participants'),
        ),
    ]
