# Generated by Django 5.1.5 on 2025-01-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entite', models.TextField()),
                ('vm_associe', models.TextField(verbose_name='Valeur métier associé')),
                ('description', models.TextField(default='description')),
                ('responsable', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evenement_redoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_associe', models.TextField(verbose_name='Valeur métier associé')),
                ('description', models.TextField(default='description')),
                ('impact', models.TextField(choices=[('social', 'Social'), ('service', 'Service'), ('juridique', 'Juridique'), ('gouvernance', 'Gouvernance'), ('financier', 'Financier'), ('reputation', 'Reputation'), ('humain', 'Humain'), ('materiel', 'Materiel')], default='reputation')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ValeurMetier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('mission', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('responsabe', models.TextField()),
                ('nature_vm', models.TextField(choices=[('processus', 'Processus'), ('information', 'Information')], default='information', verbose_name='nature ')),
            ],
        ),
        migrations.AlterField(
            model_name='atelier01',
            name='nom_societe',
            field=models.CharField(default='societe', max_length=30),
        ),
    ]
