# Generated by Django 5.1.5 on 2025-01-28 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier01', '0002_atelierparticipant_delete_biensupport_and_more'),
        ('etude', '0002_evenement_redoute_mission_socle_de_securite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier01',
            name='evenement_redoute',
            field=models.ManyToManyField(to='etude.evenement_redoute'),
        ),
        migrations.AddField(
            model_name='atelier01',
            name='mission',
            field=models.ManyToManyField(to='etude.mission', verbose_name='mission'),
        ),
        migrations.AddField(
            model_name='atelier01',
            name='socle_de_securite',
            field=models.ManyToManyField(to='etude.socle_de_securite', verbose_name='socle de sécurité'),
        ),
        migrations.AddField(
            model_name='atelier01',
            name='valeur_metier',
            field=models.ManyToManyField(to='etude.valeur_metier', verbose_name='valeur metier'),
        ),
        migrations.AddField(
            model_name='atelierparticipant',
            name='atelier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atelier01.atelier01'),
        ),
        migrations.AddField(
            model_name='atelierparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etude.participant'),
        ),
        migrations.AddField(
            model_name='atelier01',
            name='participants',
            field=models.ManyToManyField(blank=True, through='atelier01.AtelierParticipant', to='etude.participant', verbose_name='Participants'),
        ),
        migrations.DeleteModel(
            name='ValeurMetier',
        ),
    ]
