# Generated by Django 5.1.5 on 2025-01-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier01', '0002_atelier01_particiant'),
        ('etude', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atelier01',
            name='particiant',
        ),
        migrations.CreateModel(
            name='AtelierParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atelier01.atelier01')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etude.participant')),
            ],
        ),
        migrations.AddField(
            model_name='atelier01',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='ateliers', through='atelier01.AtelierParticipant', to='etude.participant', verbose_name='Participants'),
        ),
    ]
