# Generated by Django 5.1.5 on 2025-01-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier01', '0002_biensupport_evenement_redoute_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement_redoute',
            name='gravite',
            field=models.PositiveSmallIntegerField(choices=[(1, 'mineur'), (2, 'significatif'), (3, 'important'), (4, 'critique')], default=1),
        ),
    ]
