# Generated by Django 5.1.5 on 2025-01-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier01', '0003_remove_atelier01_particiant_atelierparticipant_and_more'),
        ('etude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier01',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='ateliers', through='atelier01.AtelierParticipant', to='etude.participant', verbose_name='Participants'),
        ),
    ]
