# Generated by Django 5.1.5 on 2025-01-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier01', '0003_atelier01_evenement_redoute_atelier01_mission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelierparticipant',
            name='date_joined',
            field=models.DateField(),
        ),
    ]
