# Generated by Django 5.1.5 on 2025-01-25 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier01', '0003_evenement_redoute_gravite'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='atelier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atelier01.atelier01', verbose_name='atelier'),
        ),
    ]
