# Generated by Django 5.1.5 on 2025-01-25 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier01', '0004_participant_atelier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeurmetier',
            name='responsabe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atelier01.participant', verbose_name='Entité responsable'),
        ),
    ]
