# Generated by Django 5.1.5 on 2025-01-26 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier01', '0005_alter_valeurmetier_responsabe'),
        ('etude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeurmetier',
            name='responsabe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etude.participant', verbose_name='Entité responsable'),
        ),
        migrations.AddField(
            model_name='atelier01',
            name='particiant',
            field=models.ManyToManyField(to='etude.participant'),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
