# Generated by Django 5.1.5 on 2025-01-29 10:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partie_prenante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('client', 'Client'), ('partner', 'Partner'), ('fourisseur', 'fourisseur')], max_length=32, verbose_name='Categorie')),
                ('current_dependency', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Current dependency')),
                ('current_penetration', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Current penetration')),
                ('current_maturity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Current maturity')),
                ('current_trust', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Current trust')),
            ],
        ),
        migrations.CreateModel(
            name='Atelier03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partie_prenante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atelier03.partie_prenante')),
            ],
        ),
    ]
