# Generated by Django 5.1.5 on 2025-01-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier03', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie_prenante',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='Is selected'),
        ),
        migrations.AddField(
            model_name='partie_prenante',
            name='justification',
            field=models.TextField(blank=True, verbose_name='Justification'),
        ),
    ]
