# Generated by Django 5.1.5 on 2025-01-28 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier01', '0002_atelierparticipant_delete_biensupport_and_more'),
        ('etude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement_redoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_associe', models.TextField(verbose_name='Valeur métier associé')),
                ('description', models.TextField(default='description')),
                ('impact', models.TextField(choices=[('social', 'Social'), ('service', 'Service'), ('juridique', 'Juridique'), ('gouvernance', 'Gouvernance'), ('financier', 'Financier'), ('reputation', 'Reputation'), ('humain', 'Humain'), ('materiel', 'Materiel')], default='reputation')),
                ('gravite', models.PositiveSmallIntegerField(choices=[(1, 'mineur'), (2, 'significatif'), (3, 'important'), (4, 'critique')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Socle_de_securite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referentiel', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Référentiel normatif International', 'Normatif'), ('Règlement européen sur la protection des données personnelles', 'Repdp'), ("Règles d'hygiène informatique et bonnes pratiques Française", 'Rhibp'), ("Règles de bonnes pratiques d'audit et de gouvernance Anglo-Saxon", 'Rbpag')], default='Référentiel normatif International', max_length=200)),
                ('etat', models.CharField(choices=[('appliquée avec restriction', 'Aar'), ('appliquée sans restriction', 'Asr')], default='appliquée avec restriction', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bien_support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entite', models.CharField(max_length=100)),
                ('description', models.TextField(default='description')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etude.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Etude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('atelier01', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atelier01.atelier01', verbose_name='atelier 01: Cadrage et socle de sécurité')),
            ],
        ),
        migrations.CreateModel(
            name='Valeur_metier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('mission', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('nature_vm', models.CharField(choices=[('processus', 'Processus'), ('information', 'Information')], max_length=50, verbose_name='nature ')),
                ('bien_support', models.ManyToManyField(to='etude.bien_support')),
                ('responsabe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etude.participant', verbose_name='Entité responsable')),
            ],
        ),
    ]
