# Generated by Django 5.1.5 on 2025-01-29 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier02', '0002_roto_atelier02_srov'),
        ('etude', '0003_etude_atelier02_alter_etude_atelier01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etude',
            name='atelier02',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='atelier02.atelier02', verbose_name='atelier 02: Sources de risques'),
        ),
    ]
