# Generated by Django 5.1.5 on 2025-01-30 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier03', '0002_partie_prenante_is_selected_and_more'),
        ('etude', '0004_alter_etude_atelier02'),
    ]

    operations = [
        migrations.AddField(
            model_name='etude',
            name='atelier03',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='atelier03.atelier03', verbose_name='atelier 03: Scénarios stratégiques'),
        ),
    ]
